### PR TITLE
Refresh master from upstream.

### PR DESCRIPTION
**Pull request by rbevers**
Syncs our `master` branch to the upstream `master` branch.

### CODE REVIEW

**Comment by abendig** [comment]
Would you be willing to add CI configuration?

**Comment by rbevers** [comment]
Yes. Was planning to do that in the fix branch. This was only to get an up-to-date `master` history into our repo. As a convention, should our `master` align with their `master`? Or should we have separate branch (e.g. `upstream-master`) for tracking the upstream's changes?

**Comment by abendig** [comment]
I don't know. What do you think? Generally, I think it's a good practice to pin libraries to specific versions instead of using master. But that's a different (though adjacent) issue.

**Review by abendig — APPROVED** [review]
AFAICT this is just a clean merge of upstream commits.

👍 :shipit:

**Comment by rbevers** [comment]
Yes, I'd rather have our `master` follow and match their `master` and then pin dependencies to specific commits on specific branches.

**Pull request merged**
